# syntax=docker/dockerfile:1

ARG NODE_VERSION=20-bookworm-slim

FROM node:${NODE_VERSION} AS deps
WORKDIR /repo
ENV NODE_ENV=development
ARG BUILD_TARGET=all
RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 make g++ openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY package*.json ./
COPY tsconfig.json tsconfig.packages.json ./
COPY apps ./apps
COPY packages ./packages
RUN if [ "$BUILD_TARGET" = "ws-server" ]; then \
      npm install --workspace apps/ws-server --workspace packages/engine; \
    elif [ "$BUILD_TARGET" = "web" ]; then \
      npm install --workspace apps/web --workspace packages/engine; \
    else \
      npm install; \
    fi

FROM node:${NODE_VERSION} AS build
WORKDIR /repo
ENV NODE_ENV=production
ENV NEXT_SKIP_LOCKFILE_CHECK=true
ARG BUILD_TARGET=all

# ARGs for build-time environment variables
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_DESCRIPTION
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_DEFAULT_NETWORK
ARG NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID
ARG NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_RPC_URL
ARG NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL

# Set ENV vars from ARGs so they are available to the build process
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ENV NEXT_PUBLIC_DEFAULT_NETWORK=$NEXT_PUBLIC_DEFAULT_NETWORK
ENV NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID=$NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID
ENV NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME=$NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_RPC_URL=$NEXT_PUBLIC_HYPERLIQUID_RPC_URL
ENV NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL=$NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL

# Runtime envs are injected on Cloud Run; no build-time NEXT_PUBLIC_* required.
COPY --from=deps /repo .

RUN if [ "$BUILD_TARGET" = "ws-server" ]; then \
      npm run build:packages && npm run build -w apps/ws-server; \
    elif [ "$BUILD_TARGET" = "web" ]; then \
      npm run build:packages && npm run build -w apps/web; \
    else \
      npm run build:packages && npm run build -w apps/web && npm run build -w apps/ws-server; \
    fi

FROM node:${NODE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV SERVICE=web
ENV PORT=8090
RUN apt-get update && apt-get install -y --no-install-recommends \
  openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*
COPY --from=build /repo/apps ./apps
COPY --from=build /repo/packages ./packages
COPY --from=deps /repo/node_modules ./node_modules
COPY package*.json ./
COPY start.sh ./
RUN chmod +x start.sh
CMD ["./start.sh"]

EXPOSE 8090 8099
