# syntax=docker/dockerfile:1

ARG NODE_VERSION=20-bookworm-slim

# Stage 1: Install dependencies
FROM node:${NODE_VERSION} AS deps
WORKDIR /repo
ENV NODE_ENV=development

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 make g++ openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Copy root package files
COPY package*.json ./

# Copy workspace package files (to optimize layer caching)
COPY apps/web/package*.json ./apps/web/
COPY apps/ws-server/package*.json ./apps/ws-server/
COPY apps/ws-server/prisma ./apps/ws-server/prisma
COPY packages/engine/package*.json ./packages/engine/

# Install ALL dependencies (monorepo usually needs all for workspace links)
RUN npm install

# Stage 2: Build the application
FROM node:${NODE_VERSION} AS build
WORKDIR /repo
ENV NODE_ENV=production
ENV NEXT_SKIP_LOCKFILE_CHECK=true
ARG BUILD_TARGET=all

# Build-time environment variables (required for Next.js static optimization)
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_APP_DESCRIPTION
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_DEFAULT_NETWORK
ARG NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID
ARG NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_RPC_URL
ARG NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL
ARG NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS
ARG NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL

# Set ENV vars from ARGs
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_APP_DESCRIPTION=$NEXT_PUBLIC_APP_DESCRIPTION
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ENV NEXT_PUBLIC_DEFAULT_NETWORK=$NEXT_PUBLIC_DEFAULT_NETWORK
ENV NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID=$NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID
ENV NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME=$NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_RPC_URL=$NEXT_PUBLIC_HYPERLIQUID_RPC_URL
ENV NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL=$NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL
ENV NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS=$NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS
ENV NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL=$NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL

# Copy deps and source code
COPY --from=deps /repo/node_modules ./node_modules
COPY --from=deps /repo/apps/web/node_modules ./apps/web/node_modules
COPY --from=deps /repo/apps/ws-server/node_modules ./apps/ws-server/node_modules
COPY . .

# Run build based on target
RUN if [ "$BUILD_TARGET" = "ws-server" ]; then \
      npm run build:packages && npm run build -w apps/ws-server; \
    elif [ "$BUILD_TARGET" = "web" ]; then \
      npm run build:packages && npm run build -w apps/web; \
    else \
      npm run build; \
    fi

# Stage 3: Final runner
FROM node:${NODE_VERSION} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV SERVICE=web
ENV PORT=8090

RUN apt-get update && apt-get install -y --no-install-recommends \
  openssl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Copy only necessary artifacts from build stage
COPY --from=build /repo/apps ./apps
COPY --from=build /repo/packages ./packages
COPY --from=build /repo/node_modules ./node_modules
COPY package*.json ./
COPY start.sh ./

RUN chmod +x start.sh
CMD ["./start.sh"]

EXPOSE 8090 8099
