#!/usr/bin/env node
const args = process.argv.slice(2);
if (args[0] === "config" && args[1] === "get" && args[2] === "registry") {
  console.log("https://registry.npmjs.org/");
  process.exit(0);
}
console.warn("Yarn shim invoked with unsupported arguments:", args.join(" "));
process.exit(0);
