#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/.env.generated}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing root env file: $ENV_FILE" >&2
  exit 1
fi

set -a
. "$ENV_FILE"
set +a

mkdir -p "$OUT_DIR"

urlencode() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$1" <<'PY'
import sys, urllib.parse
print(urllib.parse.quote(sys.argv[1], safe=""))
PY
    return
  fi
  if command -v node >/dev/null 2>&1; then
    node -e 'console.log(encodeURIComponent(process.argv[1]))' "$1"
    return
  fi
  echo "$1"
}

yaml_escape() {
  if command -v python3 >/dev/null 2>&1; then
    python3 - "$1" <<'PY'
import sys
value = sys.argv[1]
escaped = value.replace("\\\\", "\\\\\\\\").replace("\"", "\\\\\"")
print(f"\"{escaped}\"")
PY
    return
  fi
  local v="$1"
  v="${v//\\/\\\\}"
  v="${v//\"/\\\"}"
  printf '"%s"' "$v"
}

if [[ -n "${DB_USER:-}" && -n "${DB_PASSWORD:-}" && -n "${DB_NAME:-}" && -n "${DB_INSTANCE:-}" ]]; then
  ENCODED_USER="$(urlencode "$DB_USER")"
  ENCODED_PASS="$(urlencode "$DB_PASSWORD")"
  DATABASE_URL_EFFECTIVE="postgresql://${ENCODED_USER}:${ENCODED_PASS}@localhost/${DB_NAME}?host=/cloudsql/${PROJECT_ID}:${REGION}:${DB_INSTANCE}"
else
  DATABASE_URL_EFFECTIVE="${DATABASE_URL_CLOUD:-${DATABASE_URL:-}}"
fi

if [[ -z "${DATABASE_URL_EFFECTIVE:-}" ]]; then
  echo "Missing DATABASE_URL (or DATABASE_URL_CLOUD/DB_*)" >&2
  exit 1
fi

WEB_ENV_FILE="$OUT_DIR/env.web.env"
WS_ENV_FILE="$OUT_DIR/env.ws.env"
PRISMA_ENV_FILE="$OUT_DIR/env.prisma.env"
WEB_ENV_YAML="$OUT_DIR/env.web.yaml"
WS_ENV_YAML="$OUT_DIR/env.ws.yaml"
PRISMA_ENV_YAML="$OUT_DIR/env.prisma.yaml"

cat >"$WEB_ENV_FILE" <<EOF
SERVICE=web
NODE_ENV=production
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
WALLETCONNECT_PROJECT_ID=${WALLETCONNECT_PROJECT_ID}
NEXT_PUBLIC_DEFAULT_NETWORK=${NEXT_PUBLIC_DEFAULT_NETWORK:-}
NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID=${NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID:-}
NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME=${NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME:-}
NEXT_PUBLIC_HYPERLIQUID_RPC_URL=${NEXT_PUBLIC_HYPERLIQUID_RPC_URL:-}
NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL=${NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL:-}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME:-}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL:-}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS:-}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL:-}
EOF

cat >"$WS_ENV_FILE" <<EOF
SERVICE=ws-server
NODE_ENV=production
DATABASE_URL=${DATABASE_URL_EFFECTIVE}
ALLOWED_WS_ORIGINS=${ALLOWED_WS_ORIGINS}
DEV_ALLOWED_WS_ORIGINS=${DEV_ALLOWED_WS_ORIGINS:-}
REDIS_URL=${REDIS_URL:-}
JWT_SECRET=${JWT_SECRET:-}
CORS_ORIGINS=${CORS_ORIGINS:-}
RECONNECT_GRACE_SECONDS=${RECONNECT_GRACE_SECONDS:-}
WS_MAX_PAYLOAD=${WS_MAX_PAYLOAD:-}
EOF

cat >"$PRISMA_ENV_FILE" <<EOF
NODE_ENV=production
DATABASE_URL=${DATABASE_URL_EFFECTIVE}
EOF

cat >"$WEB_ENV_YAML" <<EOF
SERVICE: $(yaml_escape "web")
NODE_ENV: $(yaml_escape "production")
NEXT_PUBLIC_APP_URL: $(yaml_escape "${NEXT_PUBLIC_APP_URL}")
NEXT_PUBLIC_WS_URL: $(yaml_escape "${NEXT_PUBLIC_WS_URL}")
NEXT_PUBLIC_API_URL: $(yaml_escape "${NEXT_PUBLIC_API_URL}")
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: $(yaml_escape "${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}")
WALLETCONNECT_PROJECT_ID: $(yaml_escape "${WALLETCONNECT_PROJECT_ID}")
NEXT_PUBLIC_DEFAULT_NETWORK: $(yaml_escape "${NEXT_PUBLIC_DEFAULT_NETWORK:-}")
NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID:-}")
NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME:-}")
NEXT_PUBLIC_HYPERLIQUID_RPC_URL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_RPC_URL:-}")
NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL:-}")
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME:-}")
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL:-}")
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS:-}")
NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL: $(yaml_escape "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL:-}")
EOF

if [[ -z "${NEXT_PUBLIC_APP_URL:-}" || -z "${NEXT_PUBLIC_WS_URL:-}" || -z "${NEXT_PUBLIC_API_URL:-}" ]]; then
  echo "Warning: Missing NEXT_PUBLIC_* web URLs. Cloud Run web will not work until these are set." >&2
fi
if [[ -z "${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID:-}" && -z "${WALLETCONNECT_PROJECT_ID:-}" ]]; then
  echo "Warning: Missing WalletConnect project ID. Wallet connect will be disabled." >&2
fi
if [[ -z "${NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID:-}" || -z "${NEXT_PUBLIC_HYPERLIQUID_RPC_URL:-}" ]]; then
  echo "Warning: Missing Hyperliquid mainnet vars. Chain config will be incomplete." >&2
fi
if [[ -z "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID:-}" || -z "${NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL:-}" ]]; then
  echo "Warning: Missing Hyperliquid testnet vars. Testnet config will be incomplete." >&2
fi

cat >"$WS_ENV_YAML" <<EOF
SERVICE: $(yaml_escape "ws-server")
NODE_ENV: $(yaml_escape "production")
DATABASE_URL: $(yaml_escape "${DATABASE_URL_EFFECTIVE}")
ALLOWED_WS_ORIGINS: $(yaml_escape "${ALLOWED_WS_ORIGINS}")
DEV_ALLOWED_WS_ORIGINS: $(yaml_escape "${DEV_ALLOWED_WS_ORIGINS:-}")
REDIS_URL: $(yaml_escape "${REDIS_URL:-}")
JWT_SECRET: $(yaml_escape "${JWT_SECRET:-}")
CORS_ORIGINS: $(yaml_escape "${CORS_ORIGINS:-}")
RECONNECT_GRACE_SECONDS: $(yaml_escape "${RECONNECT_GRACE_SECONDS:-}")
WS_MAX_PAYLOAD: $(yaml_escape "${WS_MAX_PAYLOAD:-}")
EOF

cat >"$PRISMA_ENV_YAML" <<EOF
NODE_ENV: $(yaml_escape "production")
DATABASE_URL: $(yaml_escape "${DATABASE_URL_EFFECTIVE}")
EOF

echo "Wrote $WEB_ENV_FILE"
echo "Wrote $WS_ENV_FILE"
echo "Wrote $PRISMA_ENV_FILE"
echo "Wrote $WEB_ENV_YAML"
echo "Wrote $WS_ENV_YAML"
echo "Wrote $PRISMA_ENV_YAML"
