#!/usr/bin/env bash

# Centralized list of Next.js public environment variables
# This ensures consistency across local sync and GCP deployment scripts.

NEXT_PUBLIC_VARS=(
  "NEXT_PUBLIC_APP_NAME"
  "NEXT_PUBLIC_APP_DESCRIPTION"
  "NEXT_PUBLIC_APP_URL"
  "NEXT_PUBLIC_WS_URL"
  "NEXT_PUBLIC_API_URL"
  "NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID"
  "NEXT_PUBLIC_DEFAULT_NETWORK"
  "NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID"
  "NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME"
  "NEXT_PUBLIC_HYPERLIQUID_RPC_URL"
  "NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL"
  "NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME"
  "NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL"
  "NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS"
  "NEXT_PUBLIC_HYPERLIQUID_TESTNET_FAUCET_URL"
)

# Common WS-server variables
WS_VARS=(
  "DATABASE_URL"
  "ALLOWED_WS_ORIGINS"
  "DEV_ALLOWED_WS_ORIGINS"
  "REDIS_URL"
  "JWT_SECRET"
  "CORS_ORIGINS"
  "RECONNECT_GRACE_SECONDS"
  "WS_MAX_PAYLOAD"
  "ALLOW_UNVERIFIED_WALLETS"
)
