#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT_DIR/.env}"
WEB_ENV_FILE="${WEB_ENV_FILE:-$ROOT_DIR/apps/web/.env.local}"
WS_ENV_FILE="${WS_ENV_FILE:-$ROOT_DIR/apps/ws-server/.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing root env file: $ENV_FILE" >&2
  exit 1
fi

set -a
. "$ENV_FILE"
set +a

cat >"$WEB_ENV_FILE" <<EOF
NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=${NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID}
NEXT_PUBLIC_DEFAULT_NETWORK=${NEXT_PUBLIC_DEFAULT_NETWORK}
NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID=${NEXT_PUBLIC_HYPERLIQUID_CHAIN_ID}
NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME=${NEXT_PUBLIC_HYPERLIQUID_CHAIN_NAME}
NEXT_PUBLIC_HYPERLIQUID_RPC_URL=${NEXT_PUBLIC_HYPERLIQUID_RPC_URL}
NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL=${NEXT_PUBLIC_HYPERLIQUID_EXPLORER_URL}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_NAME}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_SYMBOL}
NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS=${NEXT_PUBLIC_HYPERLIQUID_CURRENCY_DECIMALS}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_ID}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CHAIN_NAME}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_RPC_URL}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_EXPLORER_URL}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_NAME}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_SYMBOL}
NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS=${NEXT_PUBLIC_HYPERLIQUID_TESTNET_CURRENCY_DECIMALS}
EOF

cat >"$WS_ENV_FILE" <<EOF
DATABASE_URL=${DATABASE_URL}
ALLOWED_WS_ORIGINS=${ALLOWED_WS_ORIGINS}
DEV_ALLOWED_WS_ORIGINS=${DEV_ALLOWED_WS_ORIGINS}
REDIS_URL=${REDIS_URL:-}
EOF

echo "Wrote $WEB_ENV_FILE"
echo "Wrote $WS_ENV_FILE"
